Metrics/LineLength:
  Description: Limit lines to 100 characters.
  Enabled: true
  Max: 100
  AllowURI: true
  URISchemes:
  - http
  - https

Metrics/BlockLength:
  Exclude:
    - rubocop-rspec.gemspec
    - Rakefile
    - '**/*.rake'
    - spec/**/*.rb

RSpec/NestedGroups:
  Enabled: false
  
Rspec/ExampleLength:
  Exclude:
    - spec/**/*.rb

Rspec/MultipleExpectations:
  Exclude:
    - spec/**/*.rb

Rails/ApplicationRecord:
  Enabled: false
